name: CI/CD

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Run precommit checks
        run: npx husky run precommit

      - name: Build and export
        run: npx next build && npx next export

      - name: Deploy to Vercel
        uses: vercel/actions/cli@v1
        with:
          args: deploy --prod --confirm
